ci: auto update version on release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -7,6 +7,13 @@ on:
 
 jobs:
   release:
+    strategy:
+      matrix:
+        version:
+          - major
+          - minor
+          - patch
+
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4.1.5
@@ -22,6 +29,19 @@ jobs:
 
       - name: Build
         run: pnpm prepack
+
+      - name: Update version
+        run: |
+          case ${{ matrix.version }} in
+            patch)
+              npm version patch ;;
+            minor)
+              npm version minor ;;
+            major)
+              npm version major ;;
+            *)
+              echo "Invalid version provided"; exit 1 ;;
+          esac
 
       # - name: Release
       #   run: npm publish --access public
